/*
 * Written by:
 * 
 * Liz Berberena
 * Jack Davitt
 * Shazia Mansuri
 * Simran Nanwani
 * Huda Yousef
 * 
 */

package application;

public class StartAdventure {
/*
A StartAdventure class which will have the following
i. Contains the code used to create a new game object
ii. Creates the game “environment” whether it is rooms, campuses,
etc. and fills those environments. If for example, you have the
user answer questions, the questions should be generated by
this class
iii. Displays relevant information to the user, such as “you are here”
indicator
iv. Handles commands from the user (including those that cause
exceptions)
 * */
	
	private int roomNum;
	
	public StartAdventure() {
		
		roomNum = 0;		
	}
	
	public StartAdventure(int roomNum) {
		this.roomNum = roomNum;	
	}
	
	public void setRoomNumber(int roomNum) {
		this.roomNum = roomNum;
	}
	
	public int getRoomNumber() {
		return this.roomNum;
	}
	
	public String getRoomDescription(boolean flashlight){
		String description = "";
		
		if(roomNum == 1) {
			
			if(flashlight == true) {
			description = "You wake up in the mansion lobby..."
					+ "\nYou can see a glittering key to the north and a hallway to the west. What do you want to do?";
			} else if(flashlight == false){description = "You wake up in the mansion lobby..."
					+ "\nIt's pitch dark, but you can see a light coming from the east. What do you want to do?";
			}
			
		} else if(roomNum == 2) {
			description = "You are in the bar...";
			
		} else if(roomNum == 3) {
			description = "You are in the kitchen...";
			
		} else if(roomNum == 4) {
			description = "You are in the hallway...";
			
		} else if(roomNum == 5) {
			description = "You are in the master bedroom...";
			
		} else if(roomNum == 6) {
			description = "You are in the bathroom...";
			
		} else if(roomNum == 7) {
			description = "You are outside...";
			
		}
		
		
		return description;
	}
	
	public void action(String command, boolean flashlight, boolean bottle, boolean pipe, boolean keyCar, boolean keyHall) {

		if(roomNum == 1) {
			
			if(command.equals("go north")) {
			
				if(flashlight == true) {
				
					System.out.println("You picked up a key!"); //perhaps these items can be instanced variables?
					
				} else if(flashlight == false) {
					
					System.out.println("You can't see anything.");
				}
			}
			
			if(command.equals("go east")) {
				
				this.roomNum = 2;
				System.out.println("You walk east towards the light.");
			}
			
			if(command.equals("go south")) {
				
				System.out.println("The entrance door is locked. You can't leave, but how did you get here?");
			}
			
			if(command.equals("go west")) {
				
				if(flashlight == true) {
					
					if(keyHall == true) {
							
						System.out.println("You successfully unlocked the hallway door! You proceed.");
						this.roomNum = 4;
						
					} else {
				
					System.out.println("The door to the hallway is locked. You need a key.");
					
					}
					
				} else if(flashlight == false){
					
					System.out.println("You can't see that far.");
					
				}
				
			if(command.equals("drink")) {
				
				if(bottle == false) {
					
					System.out.println("Calm down, you party animal. You don't have anything to drink.");
					
				} else {
					
					System.out.println("That was a bad idea.");
					//Make player lose health somehow!!!
					
				}
				
			}
				
			}
			
		} else if(roomNum == 2) {
			
			//if() {
				//etc...
			//}
			
			
		} else if(roomNum == 3) {
			
			
		} else if(roomNum == 4) {
			
			
		} else if(roomNum == 5) {
			
			
		} else if(roomNum == 6) {
			
			
		} else if(roomNum == 7) {
			
			
		}
		
		
		
				
		
	} //end of move() method
	
	public String getCommandList() {
		return "List of Commands:"
				+ "\ngo north"
				+ "\ngo east"
				+ "\ngo west"
				+ "\ngo south"
				+ "\ndrink"
				+ "\nattack";
	}
	
	
	
	
	
}//end of StartAdventure class
